// <auto-generated />
namespace Cocycle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class area_state_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(area_state_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "202108110623057_area_state_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
