// <auto-generated />
namespace Cocycle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes_in_arranged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_in_arranged));
        
        string IMigrationMetadata.Id
        {
            get { return "202107261257403_changes_in_arranged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
