// <auto-generated />
namespace Cocycle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_postcode_newchanges3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_postcode_newchanges3));
        
        string IMigrationMetadata.Id
        {
            get { return "202108271057139_user_postcode_newchanges3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
