// <auto-generated />
namespace Cocycle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class route_changesnew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(route_changesnew));
        
        string IMigrationMetadata.Id
        {
            get { return "202108191045085_route_changesnew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
