// <auto-generated />
namespace Cocycle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Feedback_Changed1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feedback_Changed1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108281152449_Feedback_Changed1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
